title: Bin Xu(许斌)'s Homepage(欢迎来到我的个人主页)
page-top-title: Bin Xu
top-section-bg-text: Welcome to my personal homepage
home-subtitle: Bin Xu&ensp;|&ensp;许斌
copyright-text: '&copy; Bin Xu 2024-2025. All Rights Reserved.'
